### PR TITLE
PostMessage; Add api-token support.

### PR DESCRIPTION
**Pull request by sepperousseau**
User can choose between Webhook URL or API token
API info; https://api.slack.com/methods/chat.postMessage

### CODE REVIEW

**Comment by BirmacherAkos** [comment]
Hi @sepperousseau !

Thanks for the PR.
We need to discuss this option with the team first.

**Comment by trapacska** [comment]
Hey @sepperousseau !

We've discussed with the team this and we are about to not to accept this PR. As the step already has a channel input(https://github.com/bitrise-io/steps-slack-message/blob/master/step.yml#L53) even for failed builds separately, so it would rather cause more misunderstandings then new use-cases. It would be two almost identical inputs with a special logic. For example none of the inputs can be required however at least one of them is required.

Sorry for that, otherwise the changes are great. You can still use your modified slack step if you want, just use the step ID: `- git::https://github.com/sepperousseau/steps-slack-message@feature/api-post-message:`

Thanks! 🚀

**Comment by sepperousseau** [comment]
Hi @trapacska,

I do understand that there is a 'channel' input already.
But are you aware of the fact that the 'channel' input only works with legacy incoming webhooks?
So actually the 'channel' input isn't working anymore with the new way of working with incoming webhooks. https://api.slack.com/custom-integrations/incoming-webhooks

> "The majority of your legacy code for sending messages using incoming Webhooks should continue to work within a Slack app without much modification; the only thing you can no longer do is customize the destination channel and author identity at runtime."

So I think the bot token support is the new way of working. Just want to hear you guys thought ^^

Friendly regards,

Seppe

**Comment by trapacska** [comment]
@sepperousseau we've just re-discussed this. The info you sent looks fair enough to has the step input migrated into the api token instead. We'll create a ticket in our internal tracker. You'll be notified here as soon as the development has finished.

**Pull request merged**
